try:
    raise "Some error"
finally:
    print("This is from finally")